### ISSUE TITLE
FRONTEND: Create page to adding a clothing item

### ISSUE THREAD

**Issue by aneeshaa1** [gatorcloset/OOTD#26]
- upload photo of item
- choose between main categories: tops, bottoms, one-pieces, shoes, accessories
- add tags (ex: color, sleeve-length, occasion, etc)
- submit

**Comment by michelletaing** [comment]
I made a video demo but the file is too big and I can't compress it lol so here's a screenshot of how things are looking right now:
<img width="1434" alt="Screen Shot 2023-03-18 at 1 13 11 PM" src="https://user-images.githubusercontent.com/92867456/226122313-88f90712-638d-4e09-b4a7-03f2c0da9cac.png">
When the first field is clicked, the local computer files appear and you can select from those. Once an image is selected, it will populate above the field.
<img width="730" alt="Screen Shot 2023-03-18 at 1 14 09 PM" src="https://user-images.githubusercontent.com/92867456/226122443-0d6b581c-bcac-4309-8356-f964f3584c9a.png">
The category field is a dropdown with the four categories we discussed. The clothing tags uses Angular Material's Chip's component. 
I also put together an API function that creates an Item object. It also stores the image locally onto the computer and stores the image path/name of the uploaded image.
